name: flutter_share_to_stories
description: Flutter plugin for sharing content to the Instagram Stories.
version: 0.0.1
homepage: https://github.com/Vorkytaka/flutter_share_to_stories

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: tk.vrk.flutter.share.to.flutter_share_to_stories
        pluginClass: ShareToStoriesPlugin